export default [
  "HTML", "CSS", "JScript", "React", "Node", "Ruby", "TypeScript", "Python", 
  "Vue", "Angular", "Redux", "Express", "Django", "Flask", "Sass", "Less", 
  "Webpack", "Git", "NPM", "Yarn", "Mongo", "SQL", "JSON", "REST", 
  "GraphQL", "API", "Bootstrap", "Jest", "Mocha", "ES6", "Babel", 
  "Parcel", "Vite", "Firebase", "Server", "Cloud", "Lambda", "Axios", 
  "PostCSS", "Tailwind", "JQuery", "Ember", "Vuex", "AngularJS", 
  "ReactJS", "CORS", "OAuth", "JWT", "Socket", "Promise", "Async", 
  "Await", "Event", "Fetch", "Function", "Array", "Object", "DOM", 
  "Class", "NodeJS", "Cloud9", "Heroku", "Vercel", "Travis", "Docker", 
  "Kubernetes", "GitHub", "GitLab", "Bitbucket", "Webpacker", 
  "TypeORM", "MongoDB", "MySQL", "PostgreSQL", "Redis", "SQLite", 
  "Svelte", "Prettier", "ESLint", "TypeSafe", "Vim", "Zsh", "Bash", 
  "Figma", "Sketch", "Gulp", "Grunt", "Mongo", "Netlify", "JQuery", 
  "Foundation", "Markdown", "Gatsby", "Next", "ReactNative", "Vercel", 
  "NodeMon", "Jest", "Eslint", "Pug", "Slim", "Handlebars", "Pandas", 
  "Flask", "Django", "Jinja", "SQLAlchemy", "Pillow", "NumPy", "Pytest", 
  "FastAPI", "ReactJS", "Angular", "Electron", "Cordova", "Webpack", 
  "Bootstrap", "Material", "Prisma", "GraphQL", "GitFlow", "GitOps", 
  "CSSGrid", "CSSFlex", "CSS3", "CSSModules", "SassMap", "BoxModel", 
  "Design", "Frontend", "Backend", "DevOps", "Cloud9", "Heroku", 
  "Firebase", "Jupyter", "Rust", "Swift", "GoLang", "RubyMine", "Xcode", 
  "FlaskApp", "DjangoApp", "WebApp", "CLI", "Auth", "OAuth2", "JSONP", 
  "Cache", "ArrayMap", "State", "Routing", "PWA", "Progressive", 
  "Lambda", "Serverless", "Static", "Dynamic", "EventLoop", "AsyncJS", 
  "DOMAPI", "TestCase", "TestRun", "NodeEnv", "AppServer", "ImageJS", 
  "WebSocket", "WebRTC", "TypeCheck", "ReactDOM", "ReactJSX", "Function", 
  "Promise", "Coroutine", "AsyncFunc", "RustLang", "GoLang", "Webpack4"
];
